name: Local Build Pipeline

on: [push]

env:
  APPLICATION_NAME: app2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt

      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 *.py

      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  build_image_locally:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: docker build -t ${{ env.APPLICATION_NAME }}:latest .

      - name: Save Docker image to a file
        run: docker save -o ${{ env.APPLICATION_NAME }}.tar ${{ env.APPLICATION_NAME }}:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}-image
          path: ${{ env.APPLICATION_NAME }}.tar