name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 *.py
      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  build_image_locally:
    needs: [lint]
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.build_tag.outputs.image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and tag local Docker image
        id: build_tag
        run: |
          IMAGE_NAME="local/${{ env.APPLICATION_NAME }}:latest"
          docker build -t "$IMAGE_NAME" .
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

  test_container:
    needs: [build_image_locally]
    runs-on: ubuntu-latest
    steps:
      - name: Test unit tests in container
        run: |
          docker run --rm "local/${{ env.APPLICATION_NAME }}:latest" python -m unittest --verbose --failfast
